server:
  port: 8085
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  #working on prod
  profiles:
    active: dev
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 31536000000 # a day
      refresh-token:
        expiration: 61536000000  # 1 year in milliseconds
#aws credentials
#aws:
#  accessKey: xxxx
#  secretKey: xxxx
#  region: eu-west-3
#  s3:
#    bucketName: xxxxx